#pragma once

#include "HAL/Platform.h"

#define STEREOMIX_ERROR_INTERNAL TEXT("InternalError")
#define STEREOMIX_ERROR_INVALID_INPUT TEXT("InvalidInput")

#define STEREOMIX_LOBBY FName(TEXT("LobbySession"))
#define STEREOMIX_SESSION FName(TEXT("GameSession"))
#define STEREOMIX_PARTY FName(TEXT("PartySession"))

// 대신 OSSEOS_BUCKET_ID_ATTRIBUTE_KEY 사용하기
// #define STEREOMIX_SESSIONS_SEARCH_BUCKET_ID FName(TEXT("EOS_SESSIONS_SEARCH_BUCKET_ID"))
// #define STEREOMIX_LOBBY_SEARCH_BUCKET_ID FName(TEXT("EOS_LOBBY_SEARCH_BUCKET_ID"))

#define STEREOMIX_SESSIONS_SEARCH_EMPTY_SERVERS_ONLY FName(TEXT("EOS_SESSIONS_SEARCH_EMPTY_SERVERS_ONLY"))
#define STEREOMIX_SESSIONS_SEARCH_NONEMPTY_SERVERS_ONLY FName(TEXT("EOS_SESSIONS_SEARCH_NONEMPTY_SERVERS_ONLY"))
#define STEREOMIX_SESSIONS_SEARCH_MIN_SLOTS_AVAILABLE FName(TEXT("EOS_SESSIONS_SEARCH_MINSLOTSAVAILABLE"))

#define STEREOMIX_LOBBY_NAME FName(TEXT("NAME"))

#define STEREOMIX_LOBBY_MEMBER_ID FName(TEXT("ID"))
#define STEREOMIX_LOBBY_MEMBER_NAME FName(TEXT("NAME"))
#define STEREOMIX_LOBBY_MEMBER_TEAM FName(TEXT("TEAM"))
#define STEREOMIX_LOBBY_MEMBER_PROFILE FName(TEXT("PROFILE"))
#define STEREOMIX_LOBBY_MEMBER_PLATFORM FName(TEXT("PLATFORM"))

#define STEREOMIX_MATCH_VERSION FName(TEXT("VERSION"))
#define STEREOMIX_MATCH_STATE FName(TEXT("STATE"))
#define STEREOMIX_MATCH_MODE FName(TEXT("MODE"))
#define STEREOMIX_MATCH_MAP FName(TEXT("MAP"))
#define STEREOMIX_MATCH_FQDN FName(TEXT("FQDN"))
