// Copyright Studio Surround. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace StereoMix::StereoMixOnline::LobbyEvent
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Joined)
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Left)
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kicked)
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Promoted)
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Updated)
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chat)
}
