// Copyright Studio Surround. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

// InitState
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
}

// GamePhase
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Message);

	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Round_PreRound);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Round_InRound);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Round_PostRound);

	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_CharacterSelect_Selecting);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_CharacterSelect_PostSelect);
}

// UI
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_FirstInitialized);

	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_GameMenu);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_MenuBackground);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
}

// Character
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Event_Hit);

	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Message_AttributeChanged);

	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_DoNotLanding);
}

// Buff
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Slow);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Stun);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Heal);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Damage);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Immune);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Neutralize);
}

// Stat
namespace StereoMix::Tags
{
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_CapturedTiles);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_DamageDealt);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_DamageReceived);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Kill);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Death);
	STEREOMIX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_NoiseBreakUsage);
}

namespace StereoMix::Tags
{
	/** Find a tag by string */
	STEREOMIX_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
}
